# Generated by Django 5.1.2 on 2024-11-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.game')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('characteristic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.characteristictype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='gamedata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.profiletype'),
        ),
        migrations.AddField(
            model_name='characteristictype',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.profiletype'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedata.publication'),
        ),
        migrations.CreateModel(
            name='PublishedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, help_text='If exact release date is not known', null=True)),
                ('release_month', models.PositiveSmallIntegerField(blank=True, help_text='If exact release date is not known', null=True)),
                ('sort_date', models.DateField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gamedata.publication')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The exact publication this version was found in', null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedata.publisheddocument'),
        ),
        migrations.CreateModel(
            name='RawPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_page_number', models.PositiveIntegerField()),
                ('actual_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('rules_text', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='gamedata.publisheddocument')),
            ],
        ),
        migrations.CreateModel(
            name='RawErrata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('target_page', models.CharField(max_length=13)),
                ('target_docs', models.ManyToManyField(related_name='Errata', to='gamedata.publisheddocument')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.rawpage')),
            ],
        ),
        migrations.CreateModel(
            name='RawUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='gamedata.rawpage')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='gamedata.rawunit'),
        ),
    ]
